package com.bawei.zhangjiafu1707b20200106.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.zhangjiafu1707b20200106.entity.ClsEntity;

import com.bawei.zhangjiafu1707b20200106.greendao.ClsEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clsEntityDaoConfig;

    private final ClsEntityDao clsEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clsEntityDaoConfig = daoConfigMap.get(ClsEntityDao.class).clone();
        clsEntityDaoConfig.initIdentityScope(type);

        clsEntityDao = new ClsEntityDao(clsEntityDaoConfig, this);

        registerDao(ClsEntity.class, clsEntityDao);
    }
    
    public void clear() {
        clsEntityDaoConfig.clearIdentityScope();
    }

    public ClsEntityDao getClsEntityDao() {
        return clsEntityDao;
    }

}
